"use client";
import {useEffect, useRef, useState} from "react";
import {Button, Card} from "./UI";
import {dateLabel, monthDays, scheduleEvents, shiftMonth, stockholmToday} from "../lib/schedule";
export default function EventSchedule({data, onNavigate, member = false}) {
  const today = stockholmToday();
  const [month,setMonth] = useState(today.slice(0,7));
  const [team,setTeam] = useState("");
  const [view,setView] = useState("calendar");
  const [selected,setSelected] = useState(null);
  const dialog = useRef(null);
  const events = scheduleEvents(data).filter(e => e.date.startsWith(month) && (!team || String(e.team_id) === team));
  useEffect(() => {if(selected && dialog.current && !dialog.current.open) dialog.current.showModal();},[selected]);
  function close() {dialog.current?.close(); setSelected(null);}
  return <><div className="page-heading"><div><p className="eyebrow">PLANERA VECKAN</p><h1>Klubbens kalender</h1><p className="muted">Träningar och matcher, samlade på ett ställe.</p></div>{!member && <Button onClick={()=>onNavigate("trainings")}>Hantera träningar</Button>}</div>
  <Card className="calendar-card"><div className="calendar-toolbar"><div className="button-group"><Button variant="secondary" aria-label="Föregående månad" onClick={()=>setMonth(shiftMonth(month,-1))}>‹</Button><h2>{dateLabel(`${month}-01`,{month:"long",year:"numeric"})}</h2><Button variant="secondary" aria-label="Nästa månad" onClick={()=>setMonth(shiftMonth(month,1))}>›</Button><Button variant="secondary" onClick={()=>setMonth(today.slice(0,7))}>Idag</Button></div><div className="button-group"><label className="calendar-filter">Lag<select value={team} onChange={e=>setTeam(e.target.value)}><option value="">Alla lag</option>{data.teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><div className="view-switch" aria-label="Kalendervy"><button aria-pressed={view==="calendar"} onClick={()=>setView("calendar")}>Månad</button><button aria-pressed={view==="list"} onClick={()=>setView("list")}>Lista</button></div></div></div>
  <div className="calendar-legend"><span><i className="training-dot"/>Träning</span><span><i className="match-dot"/>Match</span></div>
  {view === "calendar" ? <div className="month-grid">{["Mån","Tis","Ons","Tor","Fre","Lör","Sön"].map(d=><div className="weekday" key={d}>{d}</div>)}{monthDays(month).map((day,index)=><div key={day||`blank-${index}`} className={`month-cell ${day===today?"is-today":""} ${!day?"blank":""}`}>{day && <><span className="day-number">{Number(day.slice(-2))}</span>{events.filter(e=>e.date===day).map(e=><button className={`calendar-event ${e.kind}`} key={`${e.kind}-${e.id}`} onClick={()=>setSelected(e)}><strong>{e.time?.slice(0,5) || "Tid ej angiven"}</strong><span>{e.title}</span><small>{data.teams.find(t=>t.id===e.team_id)?.name || "Lag"}</small></button>)}</>}</div>)}</div> : <div className="event-list">{events.map(e=><button key={`${e.kind}-${e.id}`} className="event-list-row" onClick={()=>setSelected(e)}><div className="date-tile"><strong>{Number(e.date.slice(-2))}</strong><span>{dateLabel(e.date,{month:"short"})}</span></div><div><span className={`event-type ${e.kind}`}>{e.kind === "training" ? "Träning" : "Match"}</span><h3>{e.title}</h3><p className="muted">{dateLabel(e.date)} · {e.time?.slice(0,5)} · {e.location || "Plats ej angiven"}</p></div><span className="row-arrow" aria-hidden="true">↗</span></button>)}</div>}
  {!events.length && <div className="club-empty"><h3>Ingen aktivitet denna månad</h3><p>Byt månad eller lag för att se fler aktiviteter.</p></div>}</Card>
  <dialog ref={dialog} className="event-dialog" onCancel={()=>setSelected(null)} onClose={()=>setSelected(null)}>{selected && <><div className="page-heading"><span className={`event-type ${selected.kind}`}>{selected.kind==="training"?"Träning":"Match"}</span><Button variant="secondary" onClick={close} autoFocus>Stäng</Button></div><h2>{selected.title}</h2><p className="muted">{data.teams.find(t=>t.id===selected.team_id)?.name || "Lag"}</p><dl className="event-details"><div><dt>När</dt><dd>{dateLabel(selected.date,{weekday:"long",day:"numeric",month:"long"})} · {selected.time?.slice(0,5) || "Tid ej angiven"}</dd></div><div><dt>Plats</dt><dd>{selected.location || "Plats ej angiven"}</dd></div>{selected.admin_comment && <div><dt>Information</dt><dd className="preserve-lines">{selected.admin_comment}</dd></div>}</dl><Button onClick={()=>{const id=selected.kind==="training"?"trainings":"matches";close();onNavigate(id);}}>{member?"Öppna kallelser":"Hantera aktiviteten"}</Button></>}</dialog></>;
}
