"use client";
import { useState,useEffect } from "react";
import { supabase } from "../lib/supabaseClient";
import { Card,Button } from "./UI";
const initial = {technical:"",tactical:"",physical:"",psychological:"",priorities:"",goals:"",review_date:"",size:"",package:"basic",status:"ordered"};
export default function PlayerRecords({ players, kind, readOnly=false }) {
  const table=kind==="development"?"club_development":"club_equipment";
  const [selected,setSelected]=useState("");const [rows,setRows]=useState([]);const [form,setForm]=useState(initial);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  useEffect(()=>{let active=true;setRows([]);setError("");if(!selected)return;supabase.from(table).select("*").eq("player_id",selected).order("created_at",{ascending:false}).then(({data,error})=>{if(active){setRows(data||[]);setError(error?error.message:"");}});return()=>{active=false;};},[selected,table]);
  const development=kind==="development";
  function field(key,label,type="text") {return <label className="field" key={key}>{label}{type==="textarea"?<textarea required value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/>:<input required type={type} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/>}</label>;}
  async function save(e){e.preventDefault();setBusy(true);setError("");const payload=development?{technical:form.technical,tactical:form.tactical,physical:form.physical,psychological:form.psychological,priorities:form.priorities,goals:form.goals,review_date:form.review_date}:{size:form.size,package:form.package,status:form.status};const {data,error}=await supabase.from(table).insert({player_id:selected,...payload}).select();if(error)setError(error.message);else if(!data?.length)setError("Ingen post sparades. Kontrollera behörigheten.");else{setRows(prev=>[...data,...prev]);setForm(initial);}setBusy(false);}
  async function setStatus(id,status){setBusy(true);const {data,error}=await supabase.from(table).update({status}).eq("id",id).select();if(error)setError(error.message);else if(!data?.length)setError("Status kunde inte sparas.");else setRows(prev=>prev.map(r=>r.id===id?data[0]:r));setBusy(false);}
  return <><div className="page-heading"><div><p className="eyebrow">SPELARPROFIL</p><h1>{development?"Utveckling":"Utrustning"}</h1><p>{development?"Bedömning, prioriteringar och mål med bevarad historik.":"Storlek, utrustningspaket och leveransstatus."}</p></div></div>
  <Card><label className="field">Spelare<select disabled={busy} value={selected} onChange={e=>{setSelected(e.target.value);setForm(initial);}}><option value="">Välj spelare</option>{players.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></Card>
  {error && <p role="alert" className="error-banner">Kunde inte läsa eller spara: {error}</p>}
  {selected && !readOnly && <Card><form onSubmit={save}><h2>{development?"Ny utvecklingsbedömning":"Registrera utrustning"}</h2><div className="form-grid">{development?<>{field("technical","Teknik","textarea")}{field("tactical","Taktik","textarea")}{field("physical","Fysik","textarea")}{field("psychological","Psykologiska faktorer","textarea")}{field("priorities","2–3 utvecklingsprioriteringar","textarea")}{field("goals","Beteende- och prestationsmål","textarea")}{field("review_date","Nästa uppföljning","date")}</>:<>{field("size","Storlek")}<label className="field">Paket<select value={form.package} onChange={e=>setForm({...form,package:e.target.value})}><option value="basic">Träningspaket</option><option value="full">Träningspaket med jacka och ryggsäck</option></select></label><label className="field">Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="ordered">Beställd</option><option value="received">Mottagen av klubben</option><option value="delivered">Utlämnad till spelaren</option></select></label></>}</div><Button type="submit" disabled={busy}>{busy?"Sparar…":"Spara"}</Button></form></Card>}
  {selected && <Card><h2>{development?"Bedömningshistorik":"Registrerad utrustning"}</h2>{!rows.length && <p className="muted">Inga registreringar ännu.</p>}{rows.map(r=><article className="record" key={r.id}><p className="eyebrow">{new Date(r.created_at).toLocaleDateString("sv-SE")}</p>{development?<><div className="form-grid">{[["Teknik",r.technical],["Taktik",r.tactical],["Fysik",r.physical],["Psykologiska faktorer",r.psychological],["Prioriteringar",r.priorities],["Mål",r.goals]].map(([label,value])=><div key={label}><strong>{label}</strong><p className="preserve-lines">{value}</p></div>)}</div><p>Uppföljning: {r.review_date}</p></>:<><strong>{r.package==="full"?"Paket med jacka och ryggsäck":"Träningspaket"} · {r.size}</strong><p>{({ordered:"Beställd",received:"Mottagen av klubben",delivered:"Utlämnad"})[r.status]}</p>{!readOnly && <label className="field">Ändra status<select disabled={busy} value={r.status} onChange={e=>setStatus(r.id,e.target.value)}><option value="ordered">Beställd</option><option value="received">Mottagen av klubben</option><option value="delivered">Utlämnad</option></select></label>}</>}</article>)}</Card>}</>;
}
