import assert from 'node:assert/strict';
import fs from 'node:fs';
const base='data:text/javascript;base64,'+Buffer.from(fs.readFileSync('app/lib/economy.js','utf8').replace("import { csvText } from './attendance';",fs.readFileSync('app/lib/attendance.js','utf8').replaceAll('export ',''))).toString('base64');
const source=fs.readFileSync('app/lib/economy-settlements.js','utf8').replace("'./economy'",JSON.stringify(base)).replace("import { SWISH_INCOME } from './swish-income';",fs.readFileSync('app/lib/swish-income.js','utf8').replaceAll('export ',''));
const {invoiceSettlement,settlementProposal,settlementDraft,supplierAdvances}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const data={documents:[{id:'a',kind:'sponsor',amount:400,document_date:'2026-09-01'},{id:'b',kind:'sales',amount:450,document_date:'2026-09-01'},{id:'supplier',kind:'purchase',amount:1000,document_date:'2026-09-01'}],journal:[],lines:[],document_links:[],payment_links:[]};
const bank={id:'bank',amount:1000,date:'2026-09-30'};
const payments=[{id:'member',amount:150,payment_kind:'membership'}];
const allocations=[{document_id:'a',amount:400},{document_id:'b',amount:450}];
const proposal=settlementProposal(bank,allocations,['member'],data,payments);
assert.equal(proposal.remaining,0);assert.deepEqual(proposal.lines.map(l=>[l.account,l.debit,l.credit]),[['1930',1000,0],['3910',0,400],['3990',0,450],['3901',0,150]]);
assert.equal(settlementProposal(bank,[{document_id:'a',amount:200}],[],data,[]).remaining,800);
assert.throws(()=>settlementProposal(bank,[...allocations,allocations[0]],[],data,[]),/Kontrollera/);
assert.throws(()=>settlementProposal(bank,[{document_id:'supplier',amount:1000}],[],data,[]),/Kontrollera/);
assert.throws(()=>settlementProposal(bank,[{document_id:'a',amount:401}],[],data,[]),/kvarvarande/);
const posted={...data,journal:[{id:'paid',status:'posted',bank_id:'bank'}],document_links:[{journal_id:'paid',document_id:'a',amount:200}]};
assert.equal(invoiceSettlement(data.documents[0],posted).remaining,200);
assert.equal(invoiceSettlement(data.documents[0],{...posted,journal:[...posted.journal,{id:'reversal',status:'posted',bank_id:'bank'}],document_links:[...posted.document_links,{journal_id:'reversal',document_id:'a',amount:-200}]}).remaining,400);
const booked={...data,journal:[{id:'invoice',status:'posted',document_id:'a'}],lines:[{journal_id:'invoice',account:'1510',debit:400,credit:0}]};
assert.equal(settlementProposal(bank,[{document_id:'a',amount:400}],[],booked,[]).lines[1].account,'1510');
assert.equal(settlementProposal({...bank,amount:-1000},[{document_id:'supplier',amount:1000}],[],data,[]).lines[1].debit,1000);
console.log('PASS: grouped invoices plus membership, partial invoices, direction, limits, reversals and control-account settlement.');

const legacy={...data,journal:[{id:'draft',status:'draft',bank_id:'bank',document_id:'a'}],audit:[{entity_id:'draft',action:'save',at:'2026-10-08',detail:{payment_ids:['member']}}]};
assert.deepEqual(settlementDraft(bank,legacy).paymentIds,['member']);
assert.equal(settlementDraft(bank,legacy).documents[0].document_id,'a');
assert.equal(settlementDraft(bank,{...legacy,document_links:[{journal_id:'draft',document_id:'b',amount:200,account:'3990'}]}).documents[0].amount,200);
const restored={...booked,journal:[...booked.journal,{id:'legacy-paid',status:'posted',bank_id:'bank',document_id:'statement',partner_id:'partner'}],document_links:[{journal_id:'legacy-paid',document_id:'a',amount:400,account:'3910'}]};
assert.equal(invoiceSettlement(data.documents[0],restored).paid,400);
assert.equal(invoiceSettlement(data.documents[0],restored).remaining,0);
assert.equal(invoiceSettlement(data.documents[0],restored).needsCorrection,true);
assert.equal(invoiceSettlement(data.documents[0],{...restored,document_links:[{...restored.document_links[0],account:'1510'}]}).needsCorrection,false);
console.log('PASS: legacy draft choices, restored statement/partner payment links, no duplicate payment and control balance discrepancy.');

const {invoiceBookingProposal}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const supplier=data.documents[2],early={id:'early',amount:-300,date:'2026-08-14'};
const advanceProposal=settlementProposal(early,[{document_id:'supplier',amount:300}],[],data,[]);
assert.deepEqual(advanceProposal.lines,[{account:'1930',debit:0,credit:300},{account:'1480',debit:300,credit:0}]);
assert.equal(advanceProposal.remaining,0);
const advanced={...data,journal:[{id:'advance',status:'posted',bank_id:'early'}],document_links:[{journal_id:'advance',document_id:'supplier',amount:300,account:'1480'}]};
assert.equal(invoiceSettlement(supplier,advanced).advance,300);
assert.deepEqual(invoiceBookingProposal(supplier,advanced),[{account:'6990',debit:1000,credit:0},{account:'1480',debit:0,credit:300},{account:'2440',debit:0,credit:700}]);
const cleared={...advanced,journal:[...advanced.journal,{id:'invoice',status:'posted',document_id:'supplier'}],lines:[{journal_id:'invoice',account:'1480',credit:300,debit:0},{journal_id:'invoice',account:'2440',credit:700,debit:0}]};
assert.equal(invoiceSettlement(supplier,cleared).advance,0);assert.equal(invoiceSettlement(supplier,cleared).needsCorrection,false);
assert.equal(settlementProposal({...early,date:'2026-09-30',amount:-700},[{document_id:'supplier',amount:700}],[],cleared,[]).document_allocations[0].account,'2440');
const bookedAdvance={...advanced,journal:[...advanced.journal,{id:'invoice',status:'posted',document_id:'supplier'}],lines:[{journal_id:'invoice',account:'2440',credit:1000,debit:0}]};
assert.deepEqual(invoiceBookingProposal(supplier,bookedAdvance),[{account:'2440',debit:300,credit:0},{account:'1480',debit:0,credit:300}]);
const paidAdvance={...advanced,document_links:[{journal_id:'advance',document_id:'supplier',amount:1000,account:'1480'}]};
assert.deepEqual(invoiceBookingProposal(supplier,paidAdvance),[{account:'6990',debit:1000,credit:0},{account:'1480',debit:0,credit:1000}]);
console.log('PASS: earlier supplier payment, advance balance, full/partial invoice clearing and existing liability without duplicate cost.');

const split=settlementProposal({...bank,amount:850},[],['fee'],data,[{id:'fee',amount:50,payment_kind:'membership'}],[{category:'training',amount:400},{category:'clothing',amount:400}]);
assert.equal(split.remaining,0);
assert.deepEqual(split.lines.map(l=>[l.account,l.credit]),[['1930',0],['3901',50],['3902',400],['3903',400]]);
assert.throws(()=>settlementProposal({...bank,amount:-850},[],[],data,[],[{category:'training',amount:850}]),/fördelning/);
assert.throws(()=>settlementProposal(bank,[],[],data,[],[{category:'unknown',amount:20}]),/fördelning/);
assert.throws(()=>settlementProposal(bank,[],[],data,[],[{category:'kiosk',amount:1001}]),/överstiger/);
assert.deepEqual(settlementDraft(bank,{...data,journal:[{id:'split',status:'draft',bank_id:bank.id}],settlement_selections:[{journal_id:'split',payment_ids:['fee'],income_allocations:split.income_allocations}]}).incomeAllocations,split.income_allocations);
console.log('PASS: mixed membership/training/clothing, saved allocations, direction and over-allocation.');

const net=settlementProposal({...bank,amount:990},[],[],data,[],[{category:'cup',amount:500,player_id:'p1'},{category:'cup',amount:500,member_id:'m1'}],10);
assert.equal(net.remaining,0);assert.equal(net.lines.find(l=>l.account==='6570').debit,10);assert.equal(net.lines.find(l=>l.account==='3904').credit,1000);assert.equal(net.income_allocations[0].player_id,'p1');
const onlyFee=settlementProposal({...bank,amount:-25},[],[],data,[],[],25);assert.equal(onlyFee.remaining,0);assert.equal(onlyFee.lines[1].account,'6570');
const outgoingFee=settlementProposal({...bank,amount:-1010},[{document_id:'supplier',amount:1000}],[],data,[],[],10);assert.equal(outgoingFee.remaining,0);
assert.throws(()=>settlementProposal(bank,[],[],data,[],[], -1),/bankprovision/);
assert.throws(()=>settlementProposal(bank,[],[],data,[],[{category:'cup',amount:10,player_id:'p1'},{category:'cup',amount:20,player_id:'p1'}]),/fördelning/);
console.log('PASS: multi-person cup allocation, net income, standalone and supplier bank fees.');

const feeDraft={...data,journal:[{id:'feeDraft',status:'draft',bank_id:bank.id}],lines:[{journal_id:'feeDraft',account:'6570',debit:25,credit:0}],settlement_selections:[{journal_id:'feeDraft',bank_fee:0,payment_ids:[],income_allocations:[]}]};
assert.equal(settlementDraft(bank,feeDraft).bankFee,25);
assert.equal(settlementDraft(bank,{...feeDraft,document_links:[{journal_id:'feeDraft',document_id:'supplier',amount:25,account:'6570'}]}).bankFee,0);
console.log('PASS: restored standalone bank-cost drafts without counting invoice costs twice.');

const advanceReport={documents:[{id:'advance',kind:'purchase',amount:100}],journal:[{id:'paid',status:'posted',date:'2025-12-01',bank_id:'bank'},{id:'cleared',status:'posted',date:'2027-01-02',document_id:'advance'}],document_links:[{journal_id:'paid',document_id:'advance',amount:100,account:'1480'}],lines:[{journal_id:'cleared',account:'1480',credit:100,debit:0}]};
assert.equal(supplierAdvances(advanceReport,2024).length,0);
assert.equal(supplierAdvances(advanceReport,2026)[0].amount,100);
assert.equal(supplierAdvances(advanceReport,2027).length,0);
console.log('PASS: advance report includes previous-year payments and respects year-end clearing cutoff.');
