import assert from 'node:assert/strict';
import fs from 'node:fs';
const source=fs.readFileSync('app/lib/economy.js','utf8').replace("import { csvText } from './attendance';",fs.readFileSync('app/lib/attendance.js','utf8').replaceAll('export ',''));
const e=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
assert.equal(e.parseAmount('1 234,50'),1234.5);assert.equal(e.parseAmount('-1.234,50'),-1234.5);assert.throws(()=>e.parseAmount('notmoney'));
const csv=e.parseCSV('Datum;Belopp;Text;Referens\r\n2026-10-07;950,00;"Medlem; kläder";1001-2026\r\n2026-10-08;-100,00;Hall;');
assert.equal(csv.rows.length,2);assert.equal(csv.rows[0][2],'Medlem; kläder');
const rows=e.bankRows(csv,{date:'0',amount:'1',description:'2',reference:'3'});assert.equal(rows[0].amount,950);assert.equal(rows[1].amount,-100);
assert.throws(()=>e.bankRows({rows:[['2026-02-30','10']]},{date:'0',amount:'1',description:'',reference:''}));
const hashes=await e.fingerprints([rows[0],rows[0]]);assert.notEqual(hashes[0].fingerprint,hashes[1].fingerprint);assert.equal(hashes[0].fingerprint,(await e.fingerprints([rows[0]]))[0].fingerprint);
const accounts=[{code:'1930',kind:'asset'},{code:'2010',kind:'equity'},{code:'3901',kind:'income'},{code:'3001',kind:'income'},{code:'5010',kind:'expense'}];
const journal=[{id:'open',date:'2026-01-01',year:2026,status:'posted',number:1},{id:'in',date:'2026-10-07',year:2026,status:'posted',number:2,bank_id:'b'},{id:'out',date:'2026-10-08',year:2026,status:'posted',number:3},{id:'draft',date:'2026-10-08',year:2026,status:'draft'}];
const lines=[{journal_id:'open',account:'1930',debit:1000,credit:0},{journal_id:'open',account:'2010',debit:0,credit:1000},{journal_id:'in',account:'1930',debit:950,credit:0},{journal_id:'in',account:'3901',debit:0,credit:500},{journal_id:'in',account:'3001',debit:0,credit:450},{journal_id:'out',account:'5010',debit:100,credit:0},{journal_id:'out',account:'1930',debit:0,credit:100},{journal_id:'draft',account:'1930',debit:999999,credit:0}];
let r=e.report(accounts,journal,lines,2026);assert.equal(r.result,85000);assert.equal(r.bank,185000);assert.equal(r.difference,0);assert.equal(r.income,95000);assert.equal(r.equity,100000);
r=e.report(accounts,journal,lines,2027);assert.equal(r.result,0);assert.equal(r.priorResult,85000);assert.equal(r.difference,0);
assert.equal(e.matchedBank({id:'b',amount:950},journal,lines),true);
const reverse={id:'rev',date:'2026-10-07',year:2026,status:'posted',bank_id:'b'};const reversed=lines.filter(l=>l.journal_id==='in').map(l=>({...l,journal_id:'rev',credit:l.debit,debit:l.credit}));
assert.equal(e.matchedBank({id:'b',amount:950},[...journal,reverse],[...lines,...reversed]),false);
assert.equal(e.report(accounts,[...journal,reverse],[...lines,...reversed],2026).income,0);
assert.equal(e.suggestAccount({amount:150,reference:'1001-2026',description:'Member'},[],[{reference:'1001-2026',amount:150,payment_kind:'membership'}]).account,'3901');
assert.equal(e.suggestAccount({amount:-400,reference:'',description:'LEGEA'}).account,'4010');
assert.equal(e.journalRows(journal,lines,accounts).length,8);
console.log('PASS: bank CSV, Swedish amounts, duplicate hashes, split receipts, opening balances, profit, balance, prior results, drafts, reversals and proposals.');

const reportCSV=e.parseCSV('* Transaktionsrapport Period 2026-01-01 – 2026-10-08\nRadnr,Valuta,Bokfdag,Transdag,Referens,Text,Belopp,Saldo\n1,SEK,2026-10-07,2026-10-06,123,Swish,50.00,100.00\n2,SEK,2026-10-07,2026-10-06,123,Swish,50.00,50.00');
const detected=e.guessBankColumns(reportCSV.headers);
assert.equal(detected.date,'2');
const reportRows=e.bankRows(reportCSV,detected);assert.equal(reportRows.length,2);assert.equal(reportRows[0].date,'2026-10-07');
assert.equal(new Set((await e.fingerprints(reportRows)).map(r=>r.fingerprint)).size,2);
assert.equal(e.decodeBankCSV(Uint8Array.from([70,246,114,101,116,97,103])),'Företag');
assert.equal(e.decodeBankCSV(new TextEncoder().encode('Örby')),'Örby');
assert.equal(e.suggestAccount({amount:-1.5,reference:'',description:'Pris betalning'}).account,'6570');
assert.throws(()=>e.bankRows({...reportCSV,rows:[['1','EUR','2026-10-07','2026-10-06','','','50','50']]},detected),/inte i SEK/);
console.log('PASS: report preamble, bank booking dates, UTF-8/Windows-1252, repeated transactions, bank charges and currency guard.');

const invoice={id:'inv',kind:'sponsor',party:'Example Sponsor',reference:'0001',document_date:'2026-06-30',amount:1000};
const paid={id:'bank-in',date:'2026-07-30',amount:1000,description:'Bankgiro inbetalning',reference:'1234567'};
assert.equal(e.documentCandidates(paid,[invoice]).length,1);
assert.equal(e.documentCandidates({...paid,amount:-1000},[invoice]).length,0);
assert.equal(e.documentCandidates(paid,[{...invoice,is_proforma:true}]).length,0);
assert.equal(e.documentCandidates({...paid,date:'2027-07-30'},[invoice]).length,0);
assert.equal(e.documentBankProposal(paid,invoice).lines[1].account,'3910');
const bookedInvoice=[{id:'invoice-booked',status:'posted',document_id:'inv'}];
const receivable=[{journal_id:'invoice-booked',account:'1510',debit:1000,credit:0}];
assert.equal(e.documentBankProposal(paid,invoice,bookedInvoice,receivable).lines[1].account,'1510');
assert.equal(e.documentCandidates(paid,[invoice],bookedInvoice,receivable).length,1);
const settledJournal=[...bookedInvoice,{id:'payment-booked',status:'posted',document_id:'inv'}];
const settledLines=[...receivable,{journal_id:'payment-booked',account:'1510',debit:0,credit:1000}];
assert.equal(e.documentCandidates(paid,[invoice],settledJournal,settledLines).length,0);
assert.throws(()=>e.documentBankProposal(paid,invoice,settledJournal,settledLines),/redan reglerad/);
assert.throws(()=>e.documentBankProposal(paid,{...invoice,is_proforma:true}),/Proforma/);
assert.throws(()=>e.documentBankProposal({...paid,amount:-1000},invoice),/olika riktning/);
const purchase={...invoice,kind:'purchase',party:'LEGEA',id:'purchase'};
assert.equal(e.documentBankProposal({...paid,amount:-1000},purchase).lines[0].account,'4010');
assert.equal(e.documentBankProposal({...paid,amount:-1000},purchase,[{id:'p',status:'posted',document_id:'purchase'}],[{journal_id:'p',account:'2440',debit:0,credit:1000}]).lines[0].account,'2440');
console.log('PASS: invoice candidates, correct payment direction, no repeated income/cost, settled invoices and proforma guard.');
