import assert from 'node:assert/strict';
import fs from 'node:fs';
const base='data:text/javascript;base64,'+Buffer.from(fs.readFileSync('app/lib/economy.js','utf8').replace("import { csvText } from './attendance';",fs.readFileSync('app/lib/attendance.js','utf8').replaceAll('export ',''))).toString('base64');
const source=fs.readFileSync('app/lib/economy-settlements.js','utf8').replace("'./economy'",JSON.stringify(base));
const {invoiceSettlement,settlementProposal}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const data={documents:[{id:'a',kind:'sponsor',amount:400,document_date:'2026-09-01'},{id:'b',kind:'sales',amount:450,document_date:'2026-09-01'},{id:'supplier',kind:'purchase',amount:1000,document_date:'2026-09-01'}],journal:[],lines:[],document_links:[],payment_links:[]};
const bank={id:'bank',amount:1000,date:'2026-09-30'};
const payments=[{id:'member',amount:150,payment_kind:'membership'}];
const allocations=[{document_id:'a',amount:400},{document_id:'b',amount:450}];
const proposal=settlementProposal(bank,allocations,['member'],data,payments);
assert.equal(proposal.remaining,0);assert.deepEqual(proposal.lines.map(l=>[l.account,l.debit,l.credit]),[['1930',1000,0],['3910',0,400],['3990',0,450],['3901',0,150]]);
assert.equal(settlementProposal(bank,[{document_id:'a',amount:200}],[],data,[]).remaining,800);
assert.throws(()=>settlementProposal(bank,[...allocations,allocations[0]],[],data,[]),/Kontrollera/);
assert.throws(()=>settlementProposal(bank,[{document_id:'supplier',amount:1000}],[],data,[]),/Kontrollera/);
assert.throws(()=>settlementProposal(bank,[{document_id:'a',amount:401}],[],data,[]),/kvarvarande/);
const posted={...data,journal:[{id:'paid',status:'posted',bank_id:'bank'}],document_links:[{journal_id:'paid',document_id:'a',amount:200}]};
assert.equal(invoiceSettlement(data.documents[0],posted).remaining,200);
assert.equal(invoiceSettlement(data.documents[0],{...posted,journal:[...posted.journal,{id:'reversal',status:'posted',bank_id:'bank'}],document_links:[...posted.document_links,{journal_id:'reversal',document_id:'a',amount:-200}]}).remaining,400);
const booked={...data,journal:[{id:'invoice',status:'posted',document_id:'a'}],lines:[{journal_id:'invoice',account:'1510',debit:400,credit:0}]};
assert.equal(settlementProposal(bank,[{document_id:'a',amount:400}],[],booked,[]).lines[1].account,'1510');
assert.equal(settlementProposal({...bank,amount:-1000},[{document_id:'supplier',amount:1000}],[],data,[]).lines[1].debit,1000);
console.log('PASS: grouped invoices plus membership, partial invoices, direction, limits, reversals and control-account settlement.');
