import assert from 'node:assert/strict';
import fs from 'node:fs';
import { webcrypto } from 'node:crypto';
if (!globalThis.crypto) Object.defineProperty(globalThis,"crypto",{value:webcrypto});
const load=async path=>import('data:text/javascript;base64,'+Buffer.from(fs.readFileSync(path,'utf8')).toString('base64'));
const {invoiceFields}=await load('app/lib/economy-documents.js');
assert.deepEqual(invoiceFields('Leverantör: LEGEA AB\nFakturadatum: 2026-10-08\nFörfallodatum: 2026-11-08\nFakturanummer: INV-300\nAtt betala: 1 250,50 SEK'),{document_date:'2026-10-08',due_date:'2026-11-08',amount:1250.50,reference:'INV-300',party:'LEGEA AB'});
assert.equal(invoiceFields('Fakturadatum: 2026-02-30').document_date,undefined);
assert.equal(invoiceFields('Förfallodatum: 2026-11-08').document_date,undefined);
assert.equal(invoiceFields('Moms: 250,00\nBankgiro: 123-4567').amount,undefined);
const {makeBackup,verifyBackup,readStoredZip,zipStored}=await load('app/lib/economy-backup.js');
const snapshot={documents:[{name:'kvitto.pdf',path:'test/kvitto.pdf'}],journal:[{id:'j'}],audit:[]};
const bytes=await makeBackup(snapshot,async()=>new Blob(['Original evidence']));
assert.equal((await verifyBackup(bytes)).documents,1);
fs.writeFileSync('/tmp/kindmark-backup-test.zip',bytes);
const files=readStoredZip(bytes);
files['originals/test/kvitto.pdf']=new TextEncoder().encode('Modified evidence');
await assert.rejects(()=>verifyBackup(zipStored(files)),/Kontrollsumman/);
delete files['originals/test/kvitto.pdf'];await assert.rejects(()=>verifyBackup(zipStored(files)),/Kontrollsumman/);
await assert.rejects(()=>makeBackup(snapshot,async()=>{throw Error('Storage unavailable');}),/Storage unavailable/);
console.log('PASS: labelled invoice extraction, invalid date rejection, portable full backup, checksum validation and missing originals.');
