const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),React=require('react'),{renderToStaticMarkup}=require('react-dom/server'),babel=require('next/dist/compiled/babel/core');
process.env.NEXT_PUBLIC_SUPABASE_URL='https://example.supabase.co';process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY='public-test';
function load(file){const filename=path.resolve(file),code=babel.transformSync(fs.readFileSync(filename,'utf8'),{filename,configFile:false,babelrc:false,presets:[[require('next/dist/compiled/babel/preset-react'),{runtime:'automatic'}]],plugins:[require('next/dist/compiled/babel/plugin-transform-modules-commonjs')]}).code,m={exports:{}};const r=name=>name.startsWith('.')?load(path.resolve(path.dirname(filename),name+(path.extname(name)?'':fs.existsSync(path.resolve(path.dirname(filename),name+'.jsx'))?'.jsx':'.js'))):require(name);new Function('require','module','exports',code)(r,m,m.exports);return m.exports;}
const Economy=load('app/components/admin/EconomyTab.jsx').default;
const data={accounts:[{code:'1930',name:'Bank',kind:'asset'},{code:'3901',name:'Medlemsavgifter',kind:'income'}],journal:[{id:'entry',date:'2026-10-07',year:2026,status:'posted',number:1,bank_id:'bank'}],lines:[{id:'l1',journal_id:'entry',account:'1930',debit:500,credit:0},{id:'l2',journal_id:'entry',account:'3901',debit:0,credit:500}],bank:[{id:'bank',date:'2026-10-07',amount:500,description:'Testmedlem'}],documents:[],partners:[],years:[],audit:[],payment_links:[]};
for(const view of ['overview','documents','bank','partners','journal','reports']){const html=renderToStaticMarkup(React.createElement(Economy,{initialData:data,initialView:view}));assert.ok(html.includes('Ekonomi'));assert.ok(!html.includes('Läser ekonomin'));if(view==='reports'){assert.ok(html.includes('Resultaträkning'));assert.ok(html.includes('Balansräkning'));assert.ok(html.includes('Exportera huvudbok'));assert.ok(html.includes('Lås kontrollerat år'));assert.ok(html.includes('Hämta komplett säkerhetskopia'));assert.ok(html.includes('Kontrollera säkerhetskopia'));}if(view==='bank'){assert.ok(html.includes('Avstämd'));assert.ok(!html.includes('Öppna konteringsförslag'));}if(view==='documents')assert.ok(html.includes('+ Lägg till underlag'));
 if(process.argv[2]){fs.mkdirSync(process.argv[2],{recursive:true});fs.writeFileSync(path.join(process.argv[2],`${view}.html`),`<!doctype html><html lang="sv"><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>${fs.readFileSync('app/globals.css','utf8').replace(/@tailwind[^;]+;/g,'')}</style></head><body><main class="club-content">${html}</main></body></html>`);}}
const Admin=load('app/components/admin/AdminDashboard.jsx').default;
for(const role of ['admin','coach']){const html=renderToStaticMarkup(React.createElement(Admin,{user:{id:'test',email:'test@example.com'},profile:{role}}));assert.equal(html.includes('>Ekonomi</button>'),role==='admin');}
console.log('PASS: economy screens, reports, cleared bank row and admin-only navigation.');
