begin;
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"464a9f89-ae01-4c5a-98f1-5984354118d8","app_metadata":{"club_role":"admin"}}',true);
do $$declare a uuid;b uuid;bank uuid;pay uuid;eid uuid;rev uuid;draft uuid;payload jsonb;caught boolean;begin
 insert into public.club_econ_documents(name,path,kind,party,document_date,amount) values('TEST','test/'||gen_random_uuid(),'sponsor','TEST A','2099-01-01',400) returning id into a;
 insert into public.club_econ_documents(name,path,kind,party,document_date,amount) values('TEST','test/'||gen_random_uuid(),'sales','TEST B','2099-01-01',450) returning id into b;
 insert into public.club_econ_bank(date,amount,description,fingerprint,import_name) values('2099-02-01',1000,'TEST grouped','test-'||gen_random_uuid(),'TEST') returning id into bank;
 insert into public.payments(player_name,amount,status,reference,payment_kind) values('TEST member',150,'pending','TEST-GROUP','membership') returning id into pay;
 payload:=jsonb_build_object('date','2099-02-01','description','TEST grouped','bank_id',bank,'payment_ids',jsonb_build_array(pay),'document_allocations',jsonb_build_array(jsonb_build_object('document_id',a,'amount',400,'account','3910'),jsonb_build_object('document_id',b,'amount',450,'account','3990')),'lines','[{"account":"1930","debit":1000,"credit":0},{"account":"3910","debit":0,"credit":400},{"account":"3990","debit":0,"credit":450},{"account":"3901","debit":0,"credit":150}]'::jsonb);
 draft:=public.club_econ_entry('save',payload);
 if (select count(*) from public.club_econ_document_links where journal_id=draft)<>2 then raise exception 'Draft allocations missing';end if;
 if not exists(select 1 from public.club_econ_settlement_selections where journal_id=draft and payment_ids=jsonb_build_array(pay)) then raise exception 'Draft membership selection missing';end if;
 eid:=public.club_econ_entry('post',payload||jsonb_build_object('id',draft));
 if (select sum(amount) from public.club_econ_document_links where journal_id=eid)<>850 then raise exception 'Grouped allocations incorrect';end if;
 if not exists(select 1 from public.payments where id=pay and status='paid') then raise exception 'Membership not settled';end if;
 caught:=false;begin update public.club_econ_documents set amount=1 where id=a;exception when others then caught:=true;end;if not caught then raise exception 'Posted evidence editable';end if;
 caught:=false;begin perform public.club_econ_entry('post',payload);exception when others then caught:=true;end;if not caught then raise exception 'Duplicate accepted';end if;
 rev:=public.club_econ_entry('reverse',jsonb_build_object('id',eid,'date','2099-02-01','reason','TEST reverse'));
 if (select sum(amount) from public.club_econ_document_links where document_id=a)<>0 then raise exception 'Reversal allocation missing';end if;
 if not exists(select 1 from public.payments where id=pay and status='pending') then raise exception 'Membership reversal missing';end if;
 eid:=public.club_econ_entry('post',payload-'id');
 perform public.club_econ_correct(eid,'TEST correction',payload);
 if (select sum(l.amount) from public.club_econ_document_links l join public.club_econ_journal j on j.id=l.journal_id where l.document_id=a and j.status='posted')<>400 then raise exception 'Correction changed paid amount';end if;
 insert into public.club_econ_documents(name,path,kind,party,document_date,amount) values('TEST','test/'||gen_random_uuid(),'sales','TEST partial','2099-01-01',500) returning id into a;
 insert into public.club_econ_bank(date,amount,description,fingerprint,import_name) values('2099-02-01',200,'TEST partial','test-'||gen_random_uuid(),'TEST') returning id into bank;
 payload:=jsonb_build_object('date','2099-02-01','description','TEST partial','bank_id',bank,'document_allocations',jsonb_build_array(jsonb_build_object('document_id',a,'amount',200,'account','3990')),'lines','[{"account":"1930","debit":200,"credit":0},{"account":"3990","debit":0,"credit":200}]'::jsonb);
 perform public.club_econ_entry('post',payload);
 insert into public.club_econ_bank(date,amount,description,fingerprint,import_name) values('2099-02-01',400,'TEST excess','test-'||gen_random_uuid(),'TEST') returning id into bank;
 caught:=false;begin perform public.club_econ_entry('post',payload||jsonb_build_object('bank_id',bank,'document_allocations',jsonb_build_array(jsonb_build_object('document_id',a,'amount',400,'account','3990')),'lines','[{"account":"1930","debit":400,"credit":0},{"account":"3990","debit":0,"credit":400}]'::jsonb));exception when others then caught:=true;end;if not caught then raise exception 'Overpayment accepted';end if;
 insert into public.club_econ_documents(name,path,kind,party,document_date,amount) values('TEST','test/'||gen_random_uuid(),'purchase','TEST supplier','2099-01-01',300) returning id into a;
 perform public.club_econ_entry('post',jsonb_build_object('date','2099-01-01','description','TEST booked invoice','document_id',a,'lines','[{"account":"6990","debit":300,"credit":0},{"account":"2440","debit":0,"credit":300}]'::jsonb));
 insert into public.club_econ_bank(date,amount,description,fingerprint,import_name) values('2099-02-01',-300,'TEST supplier','test-'||gen_random_uuid(),'TEST') returning id into bank;
 perform public.club_econ_entry('post',jsonb_build_object('date','2099-02-01','description','TEST supplier payment','bank_id',bank,'document_allocations',jsonb_build_array(jsonb_build_object('document_id',a,'amount',300,'account','2440')),'lines','[{"account":"1930","debit":0,"credit":300},{"account":"2440","debit":300,"credit":0}]'::jsonb));
 if not (public.club_econ_snapshot()?'document_links') then raise exception 'Snapshot missing allocations';end if;
end $$;
select set_config('request.jwt.claims','{"sub":"374e427a-43bb-4944-ae3a-514b0d8569b8","app_metadata":{"club_role":"parent"}}',true);
do $$begin if exists(select 1 from public.club_econ_document_links) then raise exception 'Parent sees allocations';end if;end $$;
select 'PASS: grouped invoices/member fee, drafts, partial settlement, overpayment rejection, reversals, correction, supplier control account and parent isolation' result;
rollback;
