const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const React=require('react'),{renderToStaticMarkup}=require('react-dom/server'),babel=require('next/dist/compiled/babel/core');
function load(file){const filename=path.resolve(file);const code=babel.transformSync(fs.readFileSync(filename,'utf8'),{filename,configFile:false,babelrc:false,presets:[[require('next/dist/compiled/babel/preset-react'),{runtime:'automatic'}]],plugins:[require('next/dist/compiled/babel/plugin-transform-modules-commonjs')]}).code;const m={exports:{}};const r=name=>name.startsWith('.')?load(path.resolve(path.dirname(filename),name+(path.extname(name)?'':fs.existsSync(path.resolve(path.dirname(filename),name+'.jsx'))?'.jsx':'.js'))):require(name);new Function('require','module','exports',code)(r,m,m.exports);return m.exports;}
const Shell=load('app/components/ClubShell.jsx').default,Overview=load('app/components/admin/OverviewTab.jsx').default;
const props={tabs:[{id:'overview',label:'Översikt'},{id:'players',label:'Spelare'},{id:'teams',label:'Lag'},{id:'trainings',label:'Träningar'},{id:'attendance',label:'Närvaro'},{id:'development',label:'Utveckling'},{id:'equipment',label:'Utrustning'}],active:'overview',user:{email:'test@example.com'},role:'Admin',onChange:()=>{},onLogout:()=>{}};
const html=renderToStaticMarkup(React.createElement(Shell,props,React.createElement(Overview,{data:{players:[],teams:[],trainings:[],matches:[]},onNavigate:()=>{}})));
assert.ok(html.includes('aria-current="page"'));assert.ok(html.includes('Inga kommande träningar'));
if(process.argv[2]){fs.mkdirSync(path.dirname(process.argv[2]),{recursive:true});fs.writeFileSync(process.argv[2],`<!doctype html><html lang="sv"><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>${fs.readFileSync('app/globals.css','utf8').replace(/@tailwind[^;]+;/g,'')}</style></head><body>${html.replace('/logo.png',path.resolve('public/logo.png'))}</body></html>`);}
process.env.NEXT_PUBLIC_SUPABASE_URL='https://example.supabase.co';
process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY='test-public-key';
const Recovery=load('app/components/PasswordRecovery.jsx').default;
const resetForm=renderToStaticMarkup(React.createElement(Recovery,{user:{id:'test'},onDone:()=>{}}));
assert.ok(resetForm.includes('new-password'));assert.ok(resetForm.includes('Bekräfta lösenord'));
const expiredForm=renderToStaticMarkup(React.createElement(Recovery,{user:null,onDone:()=>{}}));
assert.ok(expiredForm.includes('Länken är ogiltig'));assert.ok(!expiredForm.includes('id="new-password"'));
const Login=load('app/components/LoginScreen.jsx').default;
assert.ok(renderToStaticMarkup(React.createElement(Login,{onLogin:()=>{}})).includes('Glömt lösenordet?'));
const Calendar=load('app/components/EventSchedule.jsx').default,Member=load('app/components/parent/MemberOverview.jsx').default;
const date = new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Stockholm'}).format(new Date());
const fixture={players:[{id:'p1',name:'Testspelare',team_id:'team1'}],teams:[{id:'team1',name:'Testlag'}],trainings:[{id:'t1',date,time:'18:30',location:'Testsal',team_id:'team1'}],matches:[{id:'m1',date,time:'19:30',opponent:'Testmotstånd',team_id:'team1'}],payments:[],messages:[]};
const calendarHTML=renderToStaticMarkup(React.createElement(Calendar,{data:fixture,onNavigate:()=>{}}));
assert.ok(calendarHTML.includes('Testmotstånd'));assert.ok(calendarHTML.includes('18:30'));assert.ok(calendarHTML.includes('Nästa månad'));assert.ok(calendarHTML.includes('Kalendervy'));
const memberHTML=renderToStaticMarkup(React.createElement(Member,{data:fixture,players:fixture.players,onNavigate:()=>{}}));
assert.ok(memberHTML.includes('Testspelare'));assert.ok(memberHTML.includes('Svara på kallelser'));assert.ok(memberHTML.includes('Inga väntande betalningar'));
const Players=load('app/components/admin/PlayersTab.jsx').default;
const rosterHTML=renderToStaticMarkup(React.createElement(Players,{data:{teams:fixture.teams,players:[{id:'roster1',name:'Roster Example',birth_year:2014,gender:'girl',number:null,team_id:null}]},onUpdate:()=>{}}));
assert.ok(rosterHTML.includes('Filtrera födelseår'));assert.ok(rosterHTML.includes('2014 · Flicka · Ej lagfördelad'));assert.ok(!rosterHTML.includes('#null'));
assert.ok(rosterHTML.includes('Lägg till förälder'));assert.ok(rosterHTML.includes('Lägg till i lag'));assert.ok(!rosterHTML.includes('Ta bort från lag'));
const assignedRoster=renderToStaticMarkup(React.createElement(Players,{data:fixture,onUpdate:()=>{}}));
assert.ok(assignedRoster.includes('Ta bort från lag'));
const coachRoster=renderToStaticMarkup(React.createElement(Players,{data:fixture,onUpdate:()=>{},readOnly:true}));
for(const label of ['Lägg till förälder','Lägg till i lag','Ta bort från lag','Ta bort spelare'])assert.ok(!coachRoster.includes(label));
const Actions=load('app/components/admin/PlayerActions.jsx').default;
const actionProps={player:fixture.players[0],teams:fixture.teams,accounts:[{id:'parent1',full_name:'Example Guardian',email:'guardian@example.com'}],onClose:()=>{},onUpdate:()=>{}};
const parentAction=renderToStaticMarkup(React.createElement(Actions,{...actionProps,mode:'parent'}));
assert.ok(parentAction.includes('Example Guardian'));assert.ok(parentAction.includes('Förälderns konto'));
const teamAction=renderToStaticMarkup(React.createElement(Actions,{...actionProps,mode:'team'}));
assert.ok(teamAction.includes('Testlag'));assert.ok(teamAction.includes('Spara lag'));
const MemberCard=load('app/components/MemberCards.jsx').MemberCard;
const activeCard=renderToStaticMarkup(React.createElement(MemberCard,{card:{name:'Example Member',member_number:'FCK-123456789ABC',status:'active'}}));
const inactiveCard=renderToStaticMarkup(React.createElement(MemberCard,{card:{name:'Example Member',member_number:'FCK-123456789ABC',status:'inactive'}}));
assert.ok(activeCard.includes('FCK-123456789ABC'));assert.ok(activeCard.includes('Kopiera rabattkod'));assert.ok(!inactiveCard.includes('Kopiera rabattkod'));assert.ok(activeCard.includes('/logo.png'));
const Matches=load('app/components/admin/MatchesTab.jsx').default;
const matchHTML=renderToStaticMarkup(React.createElement(Matches,{data:{...fixture,matches:[{...fixture.matches[0],club_score:0,opponent_score:0}]},onUpdate:()=>{}}));
assert.ok(matchHTML.includes('FC Kindmark 0–0'));assert.ok(matchHTML.includes('Öppna resultat och kallelser'));
const Fixtures=load('app/components/SupporterDashboard.jsx').SupporterFixtures;
const supporterHTML=renderToStaticMarkup(React.createElement(Fixtures,{matches:fixture.matches}));
assert.ok(supporterHTML.includes('Testmotstånd'));assert.ok(!supporterHTML.includes('Testspelare'));
console.log('PASS: overview, navigation, calendar, recovery, roster, cards, results and supporter fixtures.');

const Payments=load('app/components/admin/PaymentsTab.jsx').default,PaymentForm=load('app/components/admin/PaymentForm.jsx').default;
const paymentFixture={id:'payment1',player_id:'p1',player_name:'Testspelare',amount:150.5,status:'pending',description:'Test Fee',due_date:'2000-01-01',reference:'TEST-REF',swish:'1230830323'};
const paymentHTML=renderToStaticMarkup(React.createElement(Payments,{data:{...fixture,payments:[paymentFixture]},onUpdate:()=>{}}));
for(const text of ['Ändra','Ta bort','Markera betald','Förfallen','TEST-REF','Filtrera betalningsstatus'])assert.ok(paymentHTML.includes(text));
const paymentFormHTML=renderToStaticMarkup(React.createElement(PaymentForm,{payment:paymentFixture,players:fixture.players,onSave:()=>{},onClose:()=>{},busy:false}));
for(const text of ['Ändra betalning','Test Fee','Förfallodatum','TEST-REF','150.5'])assert.ok(paymentFormHTML.includes(text));
console.log('PASS: payment actions, overdue labels and populated edit form.');
