import assert from 'node:assert/strict';
import {privateUpdate,hashToken,randomSecret,telegramRequest} from '../supabase/functions/club-telegram/helpers.ts';
const chat={id:123,type:'private'},from={id:123,is_bot:false};
const action='12345678-1234-1234-1234-123456789012';
const callback={update_id:1,callback_query:{id:'cb',from,message:{chat},data:`r:${action}:n`}};
assert.equal(privateUpdate(callback).answer,false);
assert.equal(privateUpdate({...callback,callback_query:{...callback.callback_query,data:`r:${action}:y`}}).answer,true);
assert.equal(privateUpdate({...callback,callback_query:{...callback.callback_query,message:{chat:{...chat,type:'group'}}}}),null);
assert.equal(privateUpdate({...callback,callback_query:{...callback.callback_query,from:{id:999}}}),null);
assert.equal(privateUpdate({...callback,callback_query:{...callback.callback_query,data:'r:broken:y'}}),null);
assert.equal(privateUpdate({update_id:2,message:{from,chat,text:'/start '+ 'f'.repeat(64)}}).token,'f'.repeat(64));
assert.equal(privateUpdate({update_id:3,message:{from,chat,text:'/stop'}}).command,'stop');
assert.equal(privateUpdate({update_id:3,message:{from:{...from,is_bot:true},chat,text:'/stop'}}),null);
assert.equal((await hashToken('test')).length,64);
assert.equal(randomSecret().length,64);assert.notEqual(randomSecret(),randomSecret());
let request;
const sent=await telegramRequest('secret','sendMessage',{chat_id:123,text:'Hej'},async(url,options)=>{request={url,options};return {ok:true,status:200,json:async()=>({ok:true,result:{message_id:7}})};});
assert.equal(sent.ok,true);assert.equal(JSON.parse(request.options.body).text,'Hej');
const failed=await telegramRequest('secret','sendMessage',{},async()=>({ok:false,status:429,json:async()=>({ok:false,error_code:429,description:'Never expose secret',parameters:{retry_after:42}})}));
assert.equal(failed.retryAfter,42);assert.equal(JSON.stringify(failed).includes('secret'),false);
assert.equal((await telegramRequest('secret','getMe',{},async()=>{throw new Error('URL contains secret');})).status,503);
assert.ok(`r:${action}:y`.length<64);
console.log('PASS Telegram: private identity, RSVP buttons, deep links, random hashed tokens, delivery/retry and sanitized errors');
