"use client";
import {useCallback,useEffect,useState} from 'react';
import {supabase} from '../../lib/supabaseClient';
import {Card,Button} from '../UI';
const labels={new:'Ny anmälan',contacted:'Kontaktad',closed:'Avslutad'};
export default function InterestApplications({teams,onPlayers}){
 const [items,setItems]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[filter,setFilter]=useState('new'),[busy,setBusy]=useState(null),[notes,setNotes]=useState({}),[notice,setNotice]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');const result=await supabase.from('club_interest_applications').select('*').order('created_at',{ascending:false});if(result.error)setError(result.error.message);else{setItems(result.data||[]);setNotes(Object.fromEntries((result.data||[]).map(item=>[item.id,item.admin_note])));}setLoading(false);},[]);
 useEffect(()=>{load();},[load]);
 async function save(item,status){setBusy(item.id);setError('');setNotice('');try{const result=await supabase.from('club_interest_applications').update({status,admin_note:notes[item.id]||''}).eq('id',item.id).select('id,status,admin_note').single();if(result.error)throw result.error;setItems(old=>old.map(row=>row.id===item.id?{...row,...result.data}:row));setNotice('Anmälan är uppdaterad.');}catch(err){setError(err.message);}finally{setBusy(null);}}
 const visible=items.filter(item=>filter==='all'||item.status===filter);
 return <><div className="page-heading"><div><h1>Intresseanmälningar</h1><p>Personer som vill börja spela eller provträna.</p></div><Button variant="secondary" onClick={load} disabled={loading||!!busy}>Uppdatera</Button></div><Card><div className="interest-share"><img src="/anmalan-qr.svg" alt="QR-kod till intresseanmälan" width="112" height="112"/><div><strong>Dela anmälningsformuläret</strong><p><a href="/anmalan" target="_blank" rel="noreferrer">portal.fckindmark.se/anmalan ↗</a></p><a href="/anmalan-qr.svg" download="FC-Kindmark-Anmalan-QR.svg">Ladda ner QR-kod</a></div></div></Card><div className="button-group">{[['new',`Nya (${items.filter(i=>i.status==='new').length})`],['contacted','Kontaktade'],['closed','Avslutade'],['all','Alla']].map(([value,label])=><Button key={value} variant={filter===value?'primary':'secondary'} onClick={()=>setFilter(value)}>{label}</Button>)}</div>{error&&<p className="error-banner" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{loading?<p role="status">Hämtar anmälningar…</p>:!visible.length?<Card><p>Inga anmälningar här ännu.</p></Card>:visible.map(item=><Card key={item.id}><div className="section-heading"><h2>{item.player_name}</h2><span className="club-badge">{labels[item.status]}</span></div><p>{item.birth_date} · {teams.find(team=>team.id===item.team_id)?.name||'Lag bestäms av klubben'}</p><p className="muted">Inskickad {new Date(item.created_at).toLocaleString('sv-SE',{timeZone:'Europe/Stockholm',dateStyle:'medium',timeStyle:'short'})}</p><h3>Kontaktperson / förälder</h3><p>{item.contact_name}<br/><a href={`tel:${item.contact_phone.replace(/[^+0-9]/g,'')}`}>{item.contact_phone}</a><br/><a href={`mailto:${item.contact_email}`}>{item.contact_email}</a></p>{item.previous_club&&<p>Tidigare klubb: {item.previous_club}</p>}{item.message&&<p className="interest-message">{item.message}</p>}<label className="field">Intern anteckning<textarea rows="2" maxLength="2000" value={notes[item.id]||''} disabled={busy===item.id} onChange={e=>setNotes({...notes,[item.id]:e.target.value})}/></label><div className="button-group"><Button disabled={!!busy} variant="secondary" onClick={()=>save(item,item.status)}>Spara anteckning</Button>{item.status!=='contacted'&&<Button disabled={!!busy} onClick={()=>save(item,'contacted')}>Markera kontaktad</Button>}{item.status!=='closed'&&<Button disabled={!!busy} variant="secondary" onClick={()=>save(item,'closed')}>Avsluta</Button>}{item.status==='closed'&&<Button disabled={!!busy} variant="secondary" onClick={()=>save(item,'new')}>Öppna igen</Button>}<Button variant="secondary" onClick={onPlayers}>Öppna Spelare</Button></div><p className="muted">Lägg till spelaren under Spelare när klubben har bekräftat en plats. Intresseanmälan skapar inget spelarkonto.</p></Card>)}</>;
}
