"use client";
import {useEffect,useState} from 'react';
import {supabase} from '../../lib/supabaseClient';
import {Card,Button,Input} from '../UI';
import {sek} from '../../lib/payments';
function parsePrice(raw){if(!String(raw).trim())return null;const s=String(raw).trim().replace(',','.');if(!/^\d+(\.\d{1,2})?$/.test(s)||Number(s)<=0)throw new Error('Ange ett positivt pris med högst två decimaler.');return Number(s);}
export default function MembershipFees({members,payments,onUpdate}){
 const [year,setYear]=useState(new Date().getFullYear()),[newPrice,setNewPrice]=useState(''),[fullPrice,setFullPrice]=useState(''),[due,setDue]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[loaded,setLoaded]=useState(false);
 useEffect(()=>{let active=true;setLoaded(false);setError('');supabase.from('club_membership_prices').select('*').eq('year',year).maybeSingle().then(r=>{if(!active)return;if(r.error)setError(r.error.message);else{setNewPrice(r.data?.new_amount ?? '');setFullPrice(r.data?.full_amount ?? '');setDue(r.data?.due_date || '');setLoaded(true);}});return()=>{active=false;};},[year]);
 async function generate(){const r=await supabase.rpc('club_generate_member_fees',{fee_year:Number(year)});if(r.error)throw r.error;await onUpdate();}
 async function save(e){e.preventDefault();setBusy(true);setError('');try{const values={year:Number(year),new_amount:parsePrice(newPrice),full_amount:parsePrice(fullPrice),due_date:due || null};if(!values.new_amount&&!values.full_amount)throw new Error('Ange minst ett pris.');const r=await supabase.from('club_membership_prices').upsert(values).select('year');if(r.error || !r.data?.length)throw new Error(r.error?.message || 'Priserna kunde inte sparas.');await generate();}catch(err){setError(err.message);}finally{setBusy(false);}}
 async function changePlan(member,plan){setBusy(true);setError('');try{const r=await supabase.rpc('club_set_member_fee_plan',{target:member.id,plan,fee_year:Number(year)});if(r.error || !r.data)throw new Error(r.error?.message || 'Medlemstypen kunde inte sparas.');await generate();}catch(err){setError(err.message);}finally{setBusy(false);}}
 const playerMembers=members;
 return <Card className="payment-bank-details"><h3>Medlemsavgifter</h3><p><strong>Stödmedlem: 150 SEK per år · fast pris</strong></p><p className="muted">Nya spelare får automatiskt medlemskort och medlemsavgift för innevarande år när ett pris har sparats. Alla spelarmedlemmar visas här.</p>{error && <p role="alert" className="error-banner">{error}</p>}
 <form onSubmit={save}><fieldset disabled={busy} className="payment-fieldset"><div className="form-grid"><label className="field">Avgiftsår<select value={year} onChange={e=>setYear(Number(e.target.value))}>{Array.from({length:10},(_,i)=>new Date().getFullYear()-2+i).map(y=><option key={y} value={y}>{y}</option>)}</select></label><label className="field">Ny medlem – SEK<Input inputMode="decimal" value={newPrice} onChange={e=>setNewPrice(e.target.value)} placeholder="Ange pris"/></label><label className="field">Full medlem – SEK<Input inputMode="decimal" value={fullPrice} onChange={e=>setFullPrice(e.target.value)} placeholder="Ange pris"/></label><label className="field">Förfallodatum<Input type="date" value={due} onChange={e=>setDue(e.target.value)}/></label></div><Button type="submit" disabled={busy || !loaded}>Spara priser och skapa saknade avgifter</Button></fieldset></form>
 <p className="muted">Nya standardpriser gäller saknade och framtida avgifter. Byte av kategori justerar årets väntande avgift till kategorins pris. Betalda poster behålls. Använd Ändra för ett individuellt belopp.</p>
 <div className="payment-list">{playerMembers.map(m=>{const p=payments.find(p=>p.member_id===m.id && p.payment_kind==='membership' && Number(p.membership_year)===Number(year));return <div key={m.id} className="attendance-row"><div><strong>{m.membership_no} · {m.name}</strong><p className="muted">{p?`${sek(p.amount)} · ${p.status==='paid'?'Betald':'Väntande'}`:m.status==='inactive'?'Inaktiv medlem':'Avgift saknas'}</p></div>{m.membership_type==='supporter' ? <span>Stödmedlem · 150 SEK</span> : <label className="field">Avgiftskategori<select disabled={busy} value={m.fee_plan || 'new'} onChange={e=>changePlan(m,e.target.value)}><option value="new">Ny medlem</option><option value="full">Full medlem</option></select></label>}</div>;})}</div>
 </Card>;
}
