"use client";
import { Card, Button } from "../UI";
import { dateLabel, scheduleEvents, stockholmToday } from "../../lib/schedule";
export default function OverviewTab({ data, onNavigate, coach = false }) {
  const today = stockholmToday();
  const upcoming = scheduleEvents(data).filter(t => t.date >= today).slice(0,5);
  const unpaid = (data.payments || []).filter(p=>p.status !== "paid");
  return <><div className="page-heading"><div><p className="eyebrow">{dateLabel(today,{weekday:"long",day:"numeric",month:"long"})}</p><h1>Klubböversikt</h1><p className="muted">Din vecka i FC Kindmark börjar här.</p></div><Button onClick={() => onNavigate("calendar")}>Öppna kalendern ↗</Button></div>
  <section className="welcome-panel"><div><span className="event-type training">VÅGA GÖRA MER</span><h2>Ett lag. En gemensam riktning.</h2><p>Planera nästa aktivitet och ge spelarna bästa möjliga förutsättningar.</p><div className="button-group"><Button onClick={()=>onNavigate("trainings")}>Hantera träningar</Button><Button variant="secondary" onClick={()=>onNavigate("attendance")}>Registrera närvaro</Button></div></div><img src="/logo.png" alt="" aria-hidden="true"/></section>
  <div className="stats-grid">{[["Spelare",data.players.length,"players"],["Lag",data.teams.length,coach?"players":"teams"],["Träningar",data.trainings.length,"trainings"],["Matcher",data.matches.length,"matches"]].map(([label,value,target]) => <Card key={label} className="stat-card"><p>{label}</p><strong className="stat-value">{value}</strong><button className="text-link" onClick={()=>onNavigate(target)}>Visa {label.toLowerCase()} <span aria-hidden="true">↗</span></button></Card>)}</div>
  <div className="overview-grid"><Card><div className="section-heading"><h2>Nästa aktiviteter</h2><button className="text-link" onClick={()=>onNavigate("calendar")}>Visa alla ↗</button></div>{upcoming.length ? upcoming.map(t => <button className="event-list-row" key={`${t.kind}-${t.id}`} onClick={() => onNavigate(t.kind === "training" ? "trainings":"matches")}><div className="date-tile"><strong>{Number(t.date.slice(-2))}</strong><span>{dateLabel(t.date,{month:"short"})}</span></div><div><span className={`event-type ${t.kind}`}>{t.kind === "training" ? "Träning":"Match"}</span><h3>{t.kind === "match" ? t.title : data.teams.find(team=>team.id===t.team_id)?.name || "Träning"}</h3><p className="muted">{dateLabel(t.date,{weekday:"short"})} · {t.time?.slice(0,5)} · {t.location || "Plats ej angiven"}</p></div><span className="row-arrow" aria-hidden="true">↗</span></button>) : <div className="club-empty"><h3>Inga kommande träningar eller matcher</h3><p>Lägg in nästa aktivitet så visas den här.</p><Button onClick={()=>onNavigate("trainings")}>Öppna träningar</Button></div>}</Card>
  <div className="overview-side"><Card><div className="section-heading"><h2>Lagen</h2><span className="count-pill">{data.teams.length}</span></div>{data.teams.length ? data.teams.map(team => <button className="team-row" key={team.id} onClick={()=>onNavigate("players")}><span className="team-avatar" aria-hidden="true">{team.name?.slice(0,2)}</span><div><strong>{team.name}</strong><span className="muted">{data.players.filter(p => p.team_id === team.id).length} spelare</span></div><span className="row-arrow" aria-hidden="true">↗</span></button>):<p className="muted">Inga lag registrerade.</p>}</Card>{!coach && <Card><p className="eyebrow">ATT FÖLJA UPP</p><h2>Betalningar</h2><p className="muted">{unpaid.length ? `${unpaid.length} betalningar väntar på bekräftelse.` : "Inga väntande betalningar i registret."}</p><Button variant="secondary" onClick={()=>onNavigate("payments")}>Visa betalningar</Button></Card>}</div></div></>;
}
