"use client";
import {useState} from 'react';
import {Card,Button,Input,Select} from '../UI';
import {money,cents,matchedBank,downloadCSV} from '../../lib/economy';
import {SWISH_INCOME} from '../../lib/swish-income';
export default function SwishIncomePanel({data,year,busy,locked,onSave}){
 const [category,setCategory]=useState('kiosk'),[date,setDate]=useState(''),[search,setSearch]=useState(''),[selected,setSelected]=useState([]),[note,setNote]=useState(''),[reviewed,setReviewed]=useState(false);
 const rows=data.bank.filter(b=>b.date.startsWith(String(year)) && Number(b.amount)>0 && !matchedBank(b,data.journal,data.lines) && (!date || b.date===date) && `${b.description || ''} ${b.reference || ''}`.toLowerCase().includes(search.toLowerCase()));
 const chosen=rows.filter(b=>selected.includes(b.id)),total=chosen.reduce((n,b)=>n+cents(b.amount),0)/100;
 const summary=new Map();
 for(const j of data.journal.filter(j=>j.status==='posted' && Number(j.year)===Number(year)))for(const l of data.lines.filter(l=>l.journal_id===j.id && ['3054','3993'].includes(l.account))){const key=`${j.date}|${l.account}`;summary.set(key,(summary.get(key)||0)+cents(l.credit)-cents(l.debit));}
 const daily=[...summary].map(([key,n])=>{const [day,account]=key.split('|');return [day,account==='3054'?'Kioskförsäljning':'Gåvor',n/100];}).sort((a,b)=>b[0].localeCompare(a[0]));
 function reset(){setSelected([]);setReviewed(false);}
 async function save(action){if(await onSave({p_bank_ids:chosen.map(b=>b.id),p_category:category,p_note:note.trim(),p_action:action}))reset();}
 const disabled=busy || locked || !chosen.length || chosen.length>200 || note.trim().length<3;
 return <Card><h2>Kiosk och gåvor · Swish</h2><p>Importera bankens CSV, välj dag och markera inbetalningarna. Varje bankrad behåller datum och referens.</p><div className="economy-form"><label>Kategori<Select value={category} onChange={e=>{setCategory(e.target.value);reset();}}>{['kiosk','donation'].map(k=><option key={k} value={k}>{SWISH_INCOME[k].label}</option>)}</Select></label><label>Bankdatum (tomt = hela året)<Input type="date" value={date} onChange={e=>{setDate(e.target.value);reset();}}/></label><label>Sök banktext / referens<Input value={search} onChange={e=>{setSearch(e.target.value);reset();}}/></label><label>Beskrivning / evenemang<Input maxLength={200} value={note} placeholder="Kiosk · hemmamatch" onChange={e=>{setNote(e.target.value);setReviewed(false);}}/></label></div><div className="button-group"><Button variant="secondary" disabled={busy || locked || !rows.length} onClick={()=>{setSelected(rows.slice(0,200).map(b=>b.id));setReviewed(false);}}>Markera visade (högst 200)</Button><Button variant="secondary" disabled={busy} onClick={reset}>Avmarkera</Button></div><div className="swish-bank-list">{!rows.length && <p>Inga oavstämda inbetalningar för ditt urval.</p>}{rows.map(b=><label className="economy-check" key={b.id}><input type="checkbox" disabled={busy || locked} checked={selected.includes(b.id)} onChange={e=>{setSelected(e.target.checked?[...selected,b.id]:selected.filter(id=>id!==b.id));setReviewed(false);}}/><span>{b.date} · {b.description} · {money(b.amount)}<small>{b.reference}</small></span></label>)}</div><p><strong>{chosen.length} valda · {money(total)}</strong> · {SWISH_INCOME[category].label}</p><p>Medlemsavgifter, träningsavgifter och kläder i samma inbetalning fördelas via Stäm av på bankraden. Bankavgifter bokförs separat.</p><label className="economy-check"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/><span>Jag har kontrollerat belopp, kategori och bankunderlag. Beloppen är totalsummor inklusive eventuell moms.</span></label><div className="button-group"><Button variant="secondary" disabled={disabled} onClick={()=>save('save')}>Spara valda som utkast</Button><Button disabled={disabled || !reviewed} onClick={()=>save('post')}>Bokför valda inbetalningar</Button></div><details><summary>Bokfört per bankdag</summary>{daily.map(([day,label,n])=><p key={day+label}>{day} · {label} · {money(n)}</p>)}{!daily.length && <p>Inga bokförda kioskintäkter eller gåvor ännu.</p>}<Button variant="secondary" onClick={()=>downloadCSV(`kindmark-kiosk-gavor-${year}.csv`,[['Bankdatum','Kategori','Belopp SEK'],...daily])}>Exportera dagsöversikt</Button></details></Card>;
}
