"use client";
import {useState,useEffect} from "react";
import {supabase} from "../../lib/supabaseClient";
import {Card,Button} from "../UI";
export default function UsersTab({data}) {
  const [links,setLinks]=useState([]),[userId,setUserId]=useState(""),[playerId,setPlayerId]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
  useEffect(()=>{let active=true;supabase.from("club_player_access").select("*").then(({data,error})=>{if(active){setLinks(data||[]);setError(error?error.message:"");}});return()=>{active=false;};},[]);
  async function link(e){e.preventDefault();setBusy(true);setError("");const {data:rows,error}=await supabase.from("club_player_access").insert({user_id:userId,player_id:playerId}).select();if(error)setError(error.code==="23505"?"Spelaren är redan kopplad till kontot.":error.message);else if(!rows?.length)setError("Kopplingen sparades inte.");else setLinks(prev=>[...prev,...rows]);setBusy(false);}
  async function unlink(row){if(!confirm("Ta bort kontots koppling till spelaren?"))return;setBusy(true);setError("");const {data:removed,error}=await supabase.from("club_player_access").delete().eq("user_id",row.user_id).eq("player_id",row.player_id).select();if(error)setError(error.message);else if(!removed?.length)setError("Kopplingen kunde inte tas bort.");else setLinks(prev=>prev.filter(r=>!(r.user_id===row.user_id&&r.player_id===row.player_id)));setBusy(false);}
  return <><div className="page-heading"><div><h1>Användare</h1><p>Koppla registrerade konton till rätt spelare.</p></div></div>{error&&<p role="alert" className="error-banner">{error}</p>}<Card><form onSubmit={link}><div className="form-grid"><label className="field">Konto<select required disabled={busy} value={userId} onChange={e=>setUserId(e.target.value)}><option value="">Välj konto</option>{data.profiles.map(p=><option key={p.id} value={p.id}>{p.full_name||p.email} · {p.email}</option>)}</select></label><label className="field">Spelare<select required disabled={busy} value={playerId} onChange={e=>setPlayerId(e.target.value)}><option value="">Välj spelare</option>{data.players.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div><Button type="submit" disabled={busy}>Koppla konto</Button></form></Card><Card><h2>Spelarkopplingar</h2>{!links.length&&<p>Inga konton kopplade ännu.</p>}{links.map(r=><div className="attendance-row" key={`${r.user_id}_${r.player_id}`}><div><strong>{data.players.find(p=>String(p.id)===r.player_id)?.name||"Okänd spelare"}</strong><p>{data.profiles.find(p=>p.id===r.user_id)?.email||"Registrerat konto"}</p></div><Button disabled={busy} variant="danger" onClick={()=>unlink(r)}>Ta bort koppling</Button></div>)}</Card></>;
}
