"use client";
import {Card, Button} from "../UI";
import {dateLabel, scheduleEvents, stockholmToday} from "../../lib/schedule";
export default function MemberOverview({data, players, onNavigate, self=false}) {
 const today = stockholmToday();
 const events = scheduleEvents(data).filter(e=>e.date>=today).slice(0,4);
 const payments = data.payments.filter(p=>(players.some(c=>String(c.id)===String(p.player_id)) || (data.ownMemberIds||[]).includes(p.member_id)) && p.status!=="paid");
 return <><div className="page-heading"><div><p className="eyebrow">DIN VARDAG I FC KINDMARK</p><h1>Välkommen till klubben</h1><p className="muted">Aktiviteter, familj och klubbnyheter — samlat för dig.</p></div><Button onClick={()=>onNavigate("calendar")}>Öppna kalendern ↗</Button></div><section className="welcome-panel"><div><span className="event-type training">NÄSTA STEG</span><h2>Redo för nästa träning?</h2><p>Öppna dina kallelser och meddela tränaren vilka som kommer.</p><Button onClick={()=>onNavigate("trainings")}>Svara på kallelser</Button></div><img src="/logo.png" alt="" aria-hidden="true"/></section>
 <div className="overview-grid"><Card><div className="section-heading"><h2>På gång</h2><button className="text-link" onClick={()=>onNavigate("calendar")}>Visa kalender ↗</button></div>{events.length?events.map(e=><button key={`${e.kind}-${e.id}`} className="event-list-row" onClick={()=>onNavigate(e.kind==="training"?"trainings":"matches")}><div className="date-tile"><strong>{Number(e.date.slice(-2))}</strong><span>{dateLabel(e.date,{month:"short"})}</span></div><div><span className={`event-type ${e.kind}`}>{e.kind==="training"?"Träning":"Match"}</span><h3>{e.title}</h3><p className="muted">{dateLabel(e.date)} · {e.time?.slice(0,5)} · {e.location || "Plats ej angiven"}</p></div><span className="row-arrow" aria-hidden="true">↗</span></button>):<div className="club-empty"><h3>Inga kommande aktiviteter</h3><p>Aktiviteter för dina kopplade lag visas här.</p></div>}</Card><div className="overview-side"><Card><div className="section-heading"><h2>{self?"Min profil":"Mina spelare"}</h2><button className="text-link" onClick={()=>onNavigate("children")}>Visa profiler ↗</button></div>{players.length?players.map(p=><button className="team-row" key={p.id} onClick={()=>onNavigate("children")}><span className="team-avatar" aria-hidden="true">{p.name?.slice(0,1)}</span><div><strong>{p.name}</strong><span className="muted">{data.teams.find(t=>t.id===p.team_id)?.name || "Lag saknas"}</span></div></button>):<p className="muted">Ingen spelare kopplad ännu. Kontakta klubben för hjälp med kopplingen.</p>}</Card><Card><p className="eyebrow">DINA BETALNINGAR</p><h2>{payments.length?`${payments.length} väntande`:"Inga väntande betalningar"}</h2><p className="muted">{self?"Här ser du dina registrerade avgifter.":"Här ser du registrerade avgifter för dina spelare."}</p><Button variant="secondary" onClick={()=>onNavigate("payments")}>Visa betalningar</Button></Card><Card><h2>Från klubben</h2><p className="muted">{data.messages.length} meddelanden till dig.</p><button className="text-link" onClick={()=>onNavigate("messages")}>Öppna meddelanden ↗</button></Card></div></div></>;
}
